### ISSUE TITLE
CitizensCMD can't load correctly

### ISSUE THREAD

**Issue by Estelia-Studio** [HexedHero/CitizensCMD#19]
CitizensCMD don't work

[12:32:28 INFO]: [CitizensCMD] Enabling CitizensCMD v2.7.0
[12:32:29 INFO]: [CitizensCMD] CitizensCMD 2.7.0
[12:32:29 INFO]: [CitizensCMD] by Mateus Moreira @LichtHund & Maintained by HexedHero
[12:32:29 ERROR]: Error occurred while enabling CitizensCMD v2.7.0 (Is it up to date?)
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
        at me.mattstudios.citizenscmd.files.LangHandler.cacheMessage(LangHandler.java:72) ~[?:?]
        at me.mattstudios.citizenscmd.files.LangHandler.<init>(LangHandler.java:54) ~[?:?]
        at me.mattstudios.citizenscmd.CitizensCMD.setLang(CitizensCMD.java:314) ~[?:?]
        at me.mattstudios.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:124) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:428) ~[?:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.load(BukkitPluginUtil.java:385) ~[?:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.reload(BukkitPluginUtil.java:500) ~[?:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:125) ~[?:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[forge:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:171) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:775) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:1829) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:1664) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:39) ~[?:?]
        at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacket.java:10) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:938) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:175) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:921) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:915) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:901) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:268) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[12:32:29 INFO]: [CitizensCMD] Disabling CitizensCMD v2.7.0

**Comment by HexedHero** [comment]
Seems like you may have put an invalid lang in your config?

**Comment by Estelia-Studio** [comment]
No, config file :

check-updates: true
# 
# Available languages EN, PT, BG, RO, NO, CH
lang: EN
# 
# Toggle this on to enable using Minimessage style for message commands.
# https://docs.adventure.kyori.net/minimessage/format.html
minimessage: false
# 
# Toggle this on to enable using Minimessage style for your language files.
# https://docs.adventure.kyori.net/minimessage/format.html
minimessage-lang: false
# 
# The default npc cooldown in seconds
default-cooldown: 0
# 
# When using a NPC with price, true means that to confirm the use the player needs to seek or press shift
shift-confirm: true
# 
# Select cooldown display format, SHORT = 3m 3s | MEDIUM = 3 min 3 sec | FULL - 3 minutes 3 seconds
cooldown-time-display: MEDIUM

**Comment by Estelia-Studio** [comment]
i have put an backup on my serveur, it's work
