### ISSUE TITLE
Internal Error from Command "/npcmd remove right 0"

### ISSUE THREAD

**Issue by CrackedJustin0** [HexedHero/CitizensCMD#8]
Version: 2.6.7 on 1.19.3 with Citizens2 2.0.30-b2828

How to recreate:
Create NPC
Add a command to the NPC in my example its "/npcmd add consol gamemode creative %p%"
Then remove the index wich doenst exist with the command "/npcmd remove right 0"
Then an internal Error comes

Error:
```
[19:48:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'npcmd remove right 0' in me.mattstudios.citizenscmd.shaded.triumphteam.cmd.bukkit.BukkitCommand(npcmd)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-345]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2252) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-345]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.exceptions.CommandExecutionException: An error occurred while executing the command. On "npcmd" command on "remove" sub command.
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:184) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:104) ~[CitizensCMD-2.6.7.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
        at me.mattstudios.citizenscmd.files.DataHandler.removeCommand(DataHandler.java:438) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.commands.RemoveCommand.remove(RemoveCommand.java:84) ~[CitizensCMD-2.6.7.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.AbstractSubCommand.lambda$execute$0(AbstractSubCommand.java:182) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.execution.SyncExecutionProvider.execute(SyncExecutionProvider.java:32) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.core.AbstractSubCommand.execute(AbstractSubCommand.java:180) ~[CitizensCMD-2.6.7.jar:?]
        at me.mattstudios.citizenscmd.shaded.triumphteam.cmd.bukkit.BukkitCommand.execute(BukkitCommand.java:104) ~[CitizensCMD-2.6.7.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

**Comment by HexedHero** [comment]
Thanks!
